baseURL = "https://perceptiveshawty.github.io"
title = "Sachin Chanchani"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = ""
  copyright = "Copyright © 2022 Sachin Chanchani"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "notes"
    name = "notes"
    title = "notes"
    url = "/notes/"
    weight = 30

  # [[menu.main]]
  #   identifier = "slides"
  #   name = "slides"
  #   title = "slides"
  #   url = "/slides/"
  #   weight = 30



  # [[menu.main]]
  #   identifier = "pics"
  #   name = "pics"
  #   title = "pics"
  #   url = "/pics/"
  #   weight = 20

[permalinks]
  posts = "/:title/"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

  [markup.goldmark.renderer]
    # Allows HTML in Markdown
    unsafe = true

